SHOW GRANTS ON SCHEMA job_ads.staging;
SHOW FUTURE GRANTS IN SCHEMA job_ads.staging;
SHOW GRANTS TO ROLE job_ads_dlt_role;
SHOW GRANTS TO USER extract_loader2;

SELECT * FROM STAGING.DATA_FIELD_JOB_ADS__APPLICATION_CONTACTS;