-- Ser du att din användare har rollen?
SHOW GRANTS TO USER ERIKUNEVIK;

SHOW GRANTS TO USER extract_loader;

SHOW GRANTS TO ROLE MOVIES_DLT_ROLE;

-- Ser du att rollen har SELECT på tabellen/alla tabeller i schemat?
SHOW GRANTS TO ROLE MOVIES_READER;
SHOW GRANTS ON SCHEMA MOVIES.STAGING;

USE ROLE MOVIE_READER;
USE ROLE MOVIES_DLT_ROLE;

USE WAREHOUSE DEV_WH;
USE DATABASE MOVIES;
USE SCHEMA STAGING;

SELECT * FROM NETFLIX;


SELECT
TITLE, 
SUM(IMDB_SCORE) AS highest_score
FROM NETFLIX
WHERE GENRE ILIKE 'Drama'
GROUP BY
TITLE,
IMDB_SCORE
ORDER BY
highest_score
DESC;



